apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-08-03T17:31:37Z
  generation: 1
  labels:
    run: server
  name: server
  namespace: build
  resourceVersion: "37833"
  selfLink: /apis/extensions/v1beta1/namespaces/build/deployments/server
  uid: 132ef6bd-9743-11e8-b736-080027e6e218
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: server
    spec:
      containers:
      - image: brendanburns/go-server:first
        imagePullPolicy: IfNotPresent
        name: server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-08-03T17:31:37Z
    lastUpdateTime: 2018-08-03T17:31:37Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-08-03T17:31:37Z
    lastUpdateTime: 2018-08-03T17:31:39Z
    message: ReplicaSet "server-586cd6cb5d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
