apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-demo
  namespace: demos
spec:
  selector:
    matchLabels:
      demo: deployment
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        demo: deployment
        version: v2
    spec:
      containers:
      - name: server
        image: brendanburns/go-server:v2
        imagePullPolicy: Always
